
backend:
  name: github
  repo: 사용자이름/sciencemania  # 본인의 ID/리포지토리명으로 수정
  branch: main

media_folder: "images" # 이미지가 저장될 폴더
public_folder: "/images"

collections:
  - name: "news"
    label: "기사 작성"
    folder: "articles" # 기사가 저장될 폴더
    create: true
    extension: "json"
    format: "json"
    fields:
      - { label: "제목", name: "title", widget: "string" }
      - { label: "날짜", name: "date", widget: "datetime" }
      - { label: "작성자", name: "author", widget: "string" }
      - { label: "커버 이미지", name: "image", widget: "image", required: false }
      - { label: "본문", name: "content", widget: "markdown" }
